# Generated by Django 2.1.4 on 2019-02-16 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.CharField(max_length=12, unique=True)),
                ('title', models.CharField(max_length=1023)),
                ('release_date', models.DateTimeField()),
                ('language', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Peers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=32)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Torrent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1023)),
                ('full_magnet', models.TextField()),
                ('hash', models.CharField(max_length=64, unique=True)),
                ('size', models.CharField(max_length=16)),
                ('date_uploaded', models.DateTimeField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Movies')),
            ],
        ),
        migrations.CreateModel(
            name='TorrentHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seeds', models.IntegerField()),
                ('peers', models.IntegerField()),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('torrent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Torrent')),
            ],
        ),
        migrations.AddField(
            model_name='peers',
            name='torrent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Torrent'),
        ),
        migrations.AlterUniqueTogether(
            name='peers',
            unique_together={('torrent', 'ip')},
        ),
    ]
